import { NextResponse } from 'next/server';

export async function GET() {
  // 📦 300 AI REPLY TEMPLATES
  const templates = [
    // ===== GENERAL (50) =====
    "Thank you for your feedback! We truly appreciate your kind words.",
    "We appreciate you taking the time to share your experience with us.",
    "Thank you for your valuable feedback. We're glad you enjoyed your visit.",
    "Your feedback helps us grow. Thank you for sharing!",
    "We're so grateful for your review. Thank you for choosing us!",
    "Thank you for your honest feedback. We value your opinion.",
    "We appreciate your review and look forward to serving you again.",
    "Thanks for your feedback! It means a lot to our team.",
    "We're thrilled to hear about your experience. Thank you!",
    "Thank you for your feedback. We're always looking to improve.",
    "Thank you for your wonderful feedback! We're delighted you had a great experience.",
    "We appreciate your kind words and are glad you enjoyed your time with us.",
    "Thank you for taking the time to share your thoughts with us.",
    "Your feedback is invaluable to us. Thank you for sharing.",
    "We're so happy you had a positive experience. Thank you!",
    "Thank you for your trust and feedback. We hope to see you soon.",
    "We're grateful for your review and your support.",
    "Thank you for your feedback. We're committed to excellence.",
    "We appreciate your honest review and will use it to improve.",
    "Thank you for your feedback. We're glad you chose us!",
    "Your review made our day! Thank you for your kind words.",
    "We're truly grateful for your feedback. Thank you!",
    "Thank you for your thoughtful review. We appreciate it.",
    "We're so glad you enjoyed your experience. Thanks for sharing!",
    "Thank you for your feedback. We strive to provide the best service.",
    "We appreciate your time and your honest feedback.",
    "Thank you for your review. We're always happy to hear from you.",
    "We're delighted to receive your positive feedback. Thank you!",
    "Your feedback is a gift to us. Thank you for sharing.",
    "Thank you for your review. We look forward to welcoming you back.",
    "We appreciate your feedback and are glad you had a good time.",
    "Thank you for your thoughtful review. It means a lot to us.",
    "We're incredibly grateful for your feedback. Thank you!",
    "Thank you for your review. We're dedicated to your satisfaction.",
    "We're happy to hear you had a great experience. Thanks for sharing!",
    "Thank you for your feedback. We're always working to improve.",
    "We appreciate your kind words and your support.",
    "Thank you for your review. We'll continue to deliver great service.",
    "We're so thankful for your feedback. It helps us grow.",
    "Thank you for your honest review. We value your input.",
    "We're glad you had a positive experience. Thanks for your feedback!",
    "Thank you for your review. We're committed to your happiness.",
    "We appreciate your feedback and will use it to serve you better.",
    "Thank you for your thoughtful review. We're truly grateful.",
    "We're so happy to receive your positive feedback. Thank you!",
    "Thank you for your feedback. Your satisfaction is our priority.",
    "We appreciate your review and look forward to serving you again.",
    "Thank you for your kind words. We're delighted you enjoyed it.",
    "We're grateful for your feedback and your loyalty.",
    "Thank you for your review. We'll strive to do even better!",

    // ===== POSITIVE REVIEWS (100) =====
    "We're thrilled you had such a great experience! Thank you for your kind words.",
    "Your positive feedback means the world to us! We're so glad you enjoyed it.",
    "Thank you for your wonderful review! We're overjoyed to hear your thoughts.",
    "We're so happy to receive your glowing review! Thank you for your support.",
    "Your 5-star review made our day! We appreciate you taking the time to share.",
    "We're delighted you had such a positive experience. Thank you for your feedback.",
    "Thank you for your amazing review! We're so proud to have served you well.",
    "We're incredibly grateful for your positive feedback. It means so much to us.",
    "Your review brought smiles to our team! We're so glad you enjoyed it.",
    "Thank you for your kind and thoughtful review. We truly appreciate it.",
    "We're so happy you loved your experience with us. Thank you for sharing!",
    "Your positive review is a testament to our team's hard work. Thank you!",
    "We're thrilled to hear you had a great time. Thank you for your feedback.",
    "Thank you for your amazing review! We're so grateful for your support.",
    "We're delighted you enjoyed your visit. Your positive feedback means a lot.",
    "Thank you for your wonderful review. We're so glad you chose us.",
    "We're incredibly happy to receive your positive review. Thank you!",
    "Your review made us smile! We're so glad you had a great experience.",
    "Thank you for your glowing review. We're committed to excellence.",
    "We're so grateful for your kind words. Thank you for your feedback.",
    "We're thrilled to receive your positive feedback. Thank you for sharing!",
    "Your 5-star review is highly appreciated. We're so glad you enjoyed it.",
    "Thank you for your wonderful feedback. We're proud to have served you.",
    "We're so happy you had a great experience. Thank you for your review.",
    "Your positive feedback inspires us to do even better. Thank you!",
    "We're delighted you enjoyed our service. Your review means a lot to us.",
    "Thank you for your kind words. We're so glad we could make your day.",
    "We're incredibly grateful for your review and your support.",
    "Your review is a reflection of our commitment. Thank you for sharing!",
    "We're so happy you loved your experience. Thank you for your review.",
    "Thank you for your amazing feedback. We're thrilled you enjoyed it.",
    "We're delighted to receive your positive review. Thank you for your trust.",
    "Your review made our team's day! We're so glad you had a good time.",
    "Thank you for your generous review. We appreciate your kind words.",
    "We're so thankful for your positive feedback. It means a lot to us.",
    "Your glowing review is much appreciated. Thank you for sharing!",
    "We're thrilled you had such a wonderful experience. Thank you for your feedback.",
    "Thank you for your wonderful review. We're so glad we could serve you.",
    "We're incredibly happy to receive your kind words. Thank you for your review.",
    "Your positive review is a huge encouragement to our team. Thank you!",
    "We're delighted you enjoyed every moment. Thank you for your feedback.",
    "Thank you for your amazing review. We're so grateful for your support.",
    "We're so glad you had a positive experience. Thanks for your review!",
    "Your review means the world to us. We're so happy you enjoyed it.",
    "Thank you for your glowing feedback. We're committed to excellence.",
    "We're thrilled to receive your 5-star review. Thank you!",
    "Your kind words are truly appreciated. Thank you for your review.",
    "We're so happy we could make your experience special. Thank you!",
    "Thank you for your wonderful review. We're proud of our service.",
    "We're incredibly grateful for your positive feedback. Thank you for sharing!",
    "Your review made our day brighter. We're so glad you enjoyed it.",
    "Thank you for your generous review. We appreciate your time.",
    "We're delighted you had a wonderful experience. Thanks for your feedback!",
    "Your positive review is a reflection of our dedication. Thank you!",
    "We're so glad you loved our service. Thank you for your kind words.",
    "Thank you for your amazing feedback. We're thrilled you enjoyed it.",
    "We're incredibly happy to receive your glowing review. Thank you!",
    "Your review is a source of motivation for our team. Thank you.",
    "We're so grateful for your kind words and your support.",
    "Thank you for your wonderful review. We're glad to have served you.",
    "We're delighted you had such a great experience. Thank you for sharing!",
    "Your positive feedback is truly appreciated. Thank you for your review.",
    "We're so happy you enjoyed your time with us. Thanks for your feedback!",
    "Thank you for your generous review. We're committed to your satisfaction.",
    "We're incredibly grateful for your glowing review. Thank you!",
    "Your review brought joy to our team. We're so glad you enjoyed it.",
    "Thank you for your kind and supportive review. We appreciate it.",
    "We're so happy to receive your positive feedback. Thank you for sharing!",
    "Your review is a testament to our team's hard work. Thank you.",
    "We're delighted you loved your experience. Thanks for your review!",
    "Thank you for your wonderful review. We're thrilled to hear your thoughts.",
    "We're incredibly grateful for your kind words. Thank you for your review.",
    "Your glowing review made our day. We're so glad you enjoyed it.",
    "Thank you for your amazing feedback. We're so happy you had a great time.",
    "We're so glad you enjoyed your experience. Thanks for your review!",
    "Your positive feedback is a gift to us. Thank you for sharing.",
    "We're thrilled you had such a wonderful experience. Thank you!",
    "Thank you for your generous review. We appreciate your support.",
    "We're so happy to receive your glowing review. Thank you for your trust.",
    "Your review is a reflection of our service. Thank you for sharing.",
    "We're incredibly grateful for your positive feedback. Thank you!",
    "Thank you for your kind words. We're so glad we could make a difference.",
    "We're delighted you had a great experience. Thanks for your review!",
    "Your review made our day. We're so happy you enjoyed it.",
    "Thank you for your glowing feedback. We're committed to your happiness.",
    "We're so thankful for your review and your support.",
    "Your review is highly appreciated. We're so glad you had a good time.",
    "Thank you for your wonderful review. We're proud to have served you.",
    "We're incredibly happy to receive your feedback. Thank you for sharing.",
    "Your positive review is a motivation for our team. Thank you!",
    "We're so glad you loved your experience. Thanks for your kind words!",
    "Thank you for your generous feedback. We're thrilled you enjoyed it.",
    "We're delighted to receive your 5-star review. Thank you for your trust.",
    "Your review made our team's day. We're so glad you had a great time.",
    "Thank you for your amazing review. We're so grateful for your feedback.",
    "We're so happy you had a wonderful experience. Thank you for sharing!",
    "Your positive feedback is truly appreciated. We're so glad you enjoyed it.",
    "Thank you for your glowing review. We'll continue to deliver excellence.",
    "We're incredibly grateful for your kind words and your support.",
    "Your review is a reflection of our commitment. Thank you for sharing.",
    "We're delighted you had a great experience. Thanks for your feedback!",
    "Thank you for your generous review. We're so glad you chose us.",
    "We're so happy to receive your positive feedback. Thank you for your trust.",

    // ===== NEGATIVE REVIEWS (50) =====
    "We're sorry to hear about your experience. We'll do better next time.",
    "We apologize for the inconvenience caused. We value your feedback.",
    "We're truly sorry you didn't have a good experience. We'll improve.",
    "We appreciate your honest feedback. We're working on fixing the issues.",
    "We're sorry about your experience. We'll take your feedback seriously.",
    "We apologize for the negative experience. We're committed to improvement.",
    "We're sad to hear you didn't enjoy your visit. We'll do better.",
    "Your feedback is valuable to us. We'll use it to improve our service.",
    "We're sorry for the inconvenience. We're working to resolve this.",
    "We appreciate your honesty. We'll make sure to improve based on your feedback.",
    "We're truly sorry you had a bad experience. We'll do our best to improve.",
    "We apologize for the poor service. We're taking steps to improve.",
    "We're sorry you didn't have a positive experience. We value your feedback.",
    "Your feedback is important to us. We'll work to improve our service.",
    "We're sorry about your experience. We're committed to doing better.",
    "We apologize for any inconvenience caused. We appreciate your feedback.",
    "We're sad to hear about your bad experience. We'll make it right.",
    "We appreciate your honest review. We'll use it to improve our quality.",
    "We're sorry for the issues you faced. We're addressing them right now.",
    "We apologize for the negative experience. We hope to serve you better.",
    "We're truly sorry you weren't satisfied. We'll work to improve.",
    "Your feedback is crucial to us. We'll make the necessary changes.",
    "We're sorry about your experience. We're committed to your satisfaction.",
    "We apologize for the issues you encountered. We'll do better.",
    "We're sorry you had a bad experience. We'll take your feedback to heart.",
    "We appreciate your honest review. We'll strive to do better.",
    "We're truly sorry for the inconvenience. We value your feedback.",
    "We apologize for the poor service. We're working on improvements.",
    "We're sorry you didn't enjoy your experience. We'll make it up to you.",
    "Your feedback is invaluable. We'll use it to improve our service.",
    "We're sorry about your bad experience. We'll make things right.",
    "We apologize for the negative feedback. We're working to improve.",
    "We're sad to hear about your experience. We'll do better next time.",
    "We appreciate your honest feedback. We're taking it seriously.",
    "We're sorry for the issues you faced. We'll resolve them promptly.",
    "We apologize for the inconvenience. We're committed to improvement.",
    "We're truly sorry you had a negative experience. We'll improve.",
    "Your feedback is important to us. We'll learn from this experience.",
    "We're sorry about your negative experience. We'll work to fix it.",
    "We apologize for the poor service. We're taking corrective actions.",
    "We're sorry you didn't have a good experience. We'll do better.",
    "We appreciate your feedback. We'll use it to enhance our service.",
    "We're truly sorry for the inconvenience caused. We value your feedback.",
    "We apologize for the issues. We're committed to resolving them.",
    "We're sorry you weren't satisfied. We'll strive to improve.",
    "Your feedback is a gift to us. We'll use it to improve.",
    "We're sorry about your experience. We're dedicated to improvement.",
    "We apologize for the negative experience. We'll make it right.",
    "We're sad to hear your feedback. We'll work to earn back your trust.",
    "We appreciate your honest review. We'll take it to heart.",
    "We're sorry you faced issues. We'll address them immediately.",
    "We apologize for the inconvenience. We're grateful for your feedback.",
    "We're truly sorry you didn't enjoy your visit. We'll do better.",
    "We're sorry for the poor experience. We'll work to improve.",
    "We appreciate your candid feedback. We'll take it seriously.",
    "We're sorry for the issues you mentioned. We'll resolve them.",
    "We apologize for the bad experience. We'll make it right.",
    "We're sad to hear you were disappointed. We'll improve.",
    "Your feedback is valuable. We'll work to meet your expectations.",
    "We're sorry you weren't happy with our service. We'll do better.",
    "We apologize for the inconvenience caused. We value your input.",
    "We're truly sorry about your experience. We'll improve.",
    "We appreciate your honesty. We'll use it to grow.",
    "We're sorry about the issues. We'll resolve them as soon as possible.",
    "We apologize for the negative experience. We hope to serve you better.",
    "We're sad to hear about your bad experience. We'll make things right.",
    "Your feedback is crucial. We'll take it seriously.",
    "We're sorry for the poor service. We'll work on it.",
    "We apologize for any inconvenience. We're committed to quality.",
    "We're truly sorry you weren't satisfied. We'll improve.",
    "We appreciate your feedback. We'll do our best to improve.",
    "We're sorry about your experience. We'll work harder.",
    "We apologize for the issues. We'll fix them promptly.",
    "We're sad to hear your feedback. We'll earn back your trust.",
    "We appreciate your honesty. We'll use it to get better.",
    "We're sorry you had a bad experience. We'll make it up to you.",
    "We apologize for the negative review. We'll do better.",
    "We're truly sorry for the inconvenience. We value your feedback.",
    "We're sorry you weren't happy. We'll strive to improve.",
    "Your feedback is a learning opportunity for us. Thank you.",
    "We apologize for the poor experience. We'll work on it.",
    "We're sorry about the issues you faced. We'll resolve them.",
    "We appreciate your candid feedback. We'll learn from it.",
    "We're truly sorry you had a bad time. We'll do better.",
    "We apologize for the inconvenience. We're grateful for your feedback.",
    "We're sad to hear your feedback. We'll work to improve.",
    "We're sorry you didn't enjoy your experience. We'll improve.",
    "Your feedback is important to us. We'll take it seriously.",
    "We apologize for the negative feedback. We'll make it right.",
    "We're truly sorry you were disappointed. We'll improve.",
    "We appreciate your honest review. We'll do better next time.",
    "We're sorry for the poor service. We'll address it.",
    "We apologize for the issues. We'll resolve them.",
    "We're sad to hear you weren't satisfied. We'll work on it.",
    "Your feedback helps us grow. We'll take it to heart.",
    "We're sorry about your experience. We'll make it right.",
    "We apologize for the inconvenience. We value your feedback.",
    "We're truly sorry you didn't like it. We'll improve.",
    "We appreciate your honest feedback. We'll learn from it.",
    "We're sorry you had a bad experience. We'll do better.",
    "We apologize for the poor quality. We'll fix it.",
    "We're sad to hear your feedback. We'll earn back your trust.",
    "Your feedback is a gift. We'll use it to get better.",
    "We're sorry for the issues. We'll resolve them.",
    "We apologize for the negative experience. We'll improve.",
    "We're truly sorry you were unhappy. We'll work on it.",
    "We appreciate your feedback. We'll do better.",

    // ===== PROFESSIONAL (50) =====
    "Dear Customer, thank you for your valuable feedback. We appreciate your kind words and look forward to serving you again.",
    "Dear Valued Customer, we are grateful for your feedback. We are delighted to hear about your positive experience.",
    "Dear Guest, thank you for taking the time to share your experience with us. We truly appreciate your feedback.",
    "Dear Customer, we are thrilled to receive your positive feedback. Your satisfaction is our top priority.",
    "Dear Valued Guest, we appreciate your honest feedback. We are committed to providing excellent service.",
    "Dear Customer, thank you for your review. We are glad we could meet your expectations.",
    "Dear Guest, we value your feedback and are delighted to hear about your positive experience.",
    "Dear Valued Customer, we appreciate your kind words and your trust in us.",
    "Dear Customer, thank you for your thoughtful review. We strive to deliver the best experience.",
    "Dear Guest, we are grateful for your feedback. We hope to welcome you back soon.",
    "Dear Valued Customer, your feedback is invaluable to us. We appreciate your time.",
    "Dear Customer, we are thrilled you had a great experience. Thank you for your review.",
    "Dear Guest, we appreciate your honest review. Your feedback helps us improve.",
    "Dear Valued Guest, thank you for your positive feedback. We are delighted you enjoyed it.",
    "Dear Customer, we are happy to receive your positive review. Your satisfaction drives us.",
    "Dear Guest, we are truly grateful for your feedback. We look forward to serving you again.",
    "Dear Valued Customer, thank you for your wonderful review. We are proud of our service.",
    "Dear Customer, your positive feedback is highly appreciated. We are so glad you enjoyed it.",
    "Dear Guest, we are delighted to hear about your good experience. Thank you.",
    "Dear Valued Guest, we appreciate your review and are committed to your satisfaction.",
    "Dear Customer, we are incredibly grateful for your kind words. Thank you.",
    "Dear Guest, thank you for your feedback. We are dedicated to providing great service.",
    "Dear Valued Customer, we are thrilled you had a positive experience. Thank you.",
    "Dear Customer, we appreciate your feedback and are glad you chose us.",
    "Dear Guest, your review means a lot to us. We are so happy you enjoyed it.",
    "Dear Valued Guest, thank you for your generous review. We value your trust.",
    "Dear Customer, we are so glad to hear about your great experience. Thank you.",
    "Dear Guest, we appreciate your positive feedback and look forward to seeing you again.",
    "Dear Valued Customer, your feedback is a gift to us. We are grateful.",
    "Dear Customer, we are delighted to receive your wonderful review. Thank you.",
    "Dear Guest, we appreciate your time and your thoughtful feedback.",
    "Dear Valued Guest, we are proud to have served you. Thank you for your review.",
    "Dear Customer, we are committed to your satisfaction and value your feedback.",
    "Dear Guest, we are thrilled you enjoyed your experience. Thank you.",
    "Dear Valued Customer, your review is a reflection of our efforts. Thank you.",
    "Dear Customer, we appreciate your kind words and your support.",
    "Dear Guest, we are so happy you had a great time. Thanks for sharing.",
    "Dear Valued Guest, we are grateful for your review and your loyalty.",
    "Dear Customer, we are delighted you had such a positive experience.",
    "Dear Guest, thank you for your wonderful feedback. We appreciate it.",
    "Dear Valued Customer, we are so glad we could serve you. Thank you.",
    "Dear Customer, we are thrilled to hear about your positive experience.",
    "Dear Guest, we appreciate your honest review. We value your input.",
    "Dear Valued Guest, thank you for your thoughtful review. We are grateful.",
    "Dear Customer, we are delighted to receive your positive feedback.",
    "Dear Guest, we are so happy to hear about your good experience.",
    "Dear Valued Customer, we appreciate your review and your trust in us.",
    "Dear Customer, thank you for your generous review. We are humbled.",
    "Dear Guest, we are truly grateful for your feedback. Thank you.",
    "Dear Valued Guest, we are committed to providing excellent service.",
    "Dear Customer, we appreciate your feedback and are glad you enjoyed it.",
    "Dear Guest, we are so happy you had a great experience. Thank you.",
    "Dear Valued Customer, your review is greatly appreciated. Thank you.",
    "Dear Customer, we are thrilled to have served you. Thank you.",
    "Dear Guest, we are delighted to hear your feedback. We value it.",
    "Dear Valued Guest, thank you for your positive review. We are grateful.",
    "Dear Customer, we are committed to exceeding your expectations. Thank you.",
    "Dear Guest, we appreciate your honest review. It helps us grow.",
    "Dear Valued Customer, we are so glad you enjoyed your visit. Thank you.",
    "Dear Customer, we are grateful for your feedback. We hope to see you soon.",
    "Dear Guest, thank you for your wonderful review. We appreciate your time.",
    "Dear Valued Guest, we are delighted to receive your feedback.",
    "Dear Customer, we are so happy you loved our service. Thank you.",
    "Dear Guest, we value your feedback and are committed to improvement.",
    "Dear Valued Customer, we are thrilled to hear about your positive experience.",
    "Dear Customer, your feedback is a testament to our quality. Thank you.",
    "Dear Guest, we are so grateful for your review and your support.",
    "Dear Valued Guest, we are delighted you enjoyed your time with us.",
    "Dear Customer, thank you for your generous feedback. We are humbled.",
    "Dear Guest, we appreciate your positive feedback. It means a lot.",
    "Dear Valued Customer, we are so glad we could make your day.",
    "Dear Customer, we are delighted to receive your wonderful review.",
    "Dear Guest, thank you for your honest review. We are truly grateful.",
    "Dear Valued Guest, we appreciate your review and look forward to serving you again.",
    "Dear Customer, we are thrilled you had a great experience. Thank you.",
    "Dear Guest, we are happy to hear about your positive feedback.",
    "Dear Valued Customer, we are committed to your happiness. Thank you.",
    "Dear Customer, we are so glad you enjoyed your experience. Thank you.",
    "Dear Guest, we appreciate your feedback and are grateful for your trust.",
    "Dear Valued Guest, thank you for your kind words. We value them.",
    "Dear Customer, we are delighted to have served you. Thank you.",
    "Dear Guest, we are so happy you had a good time. Thank you.",
    "Dear Valued Customer, we are grateful for your feedback. We hope to welcome you back.",
    "Dear Customer, we appreciate your review and your time.",
    "Dear Guest, we are thrilled to receive your positive feedback.",
    "Dear Valued Guest, we are so glad we could meet your expectations.",
    "Dear Customer, thank you for your generous review. We are truly grateful.",
    "Dear Guest, we are committed to your satisfaction and value your feedback.",
    "Dear Valued Customer, we are delighted to hear about your great experience.",
    "Dear Customer, we are so happy you chose us. Thank you.",
    "Dear Guest, we appreciate your honest review. We'll use it to improve.",
    "Dear Valued Guest, we are so glad you had a positive experience.",
    "Dear Customer, we are grateful for your feedback. We hope to see you again.",
    "Dear Guest, thank you for your wonderful review. We are humbled.",
    "Dear Valued Customer, we are proud of our service and glad you enjoyed it.",
    "Dear Customer, we are thrilled to receive your positive feedback.",
    "Dear Guest, we are so happy you enjoyed your experience.",
    "Dear Valued Guest, we appreciate your feedback and are committed to excellence.",
    "Dear Customer, your review is a gift to us. Thank you for sharing.",
    "Dear Guest, we are delighted you had a good experience. Thank you.",
    "Dear Valued Customer, we are so glad we could serve you well.",
  ];

  return NextResponse.json({ success: true, templates });
}
