export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-zinc-100 dark:bg-black text-black dark:text-white p-8">

      <div className="max-w-4xl mx-auto bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-3xl p-8">

        <h1 className="text-4xl font-bold mb-2">
          Disclaimer
        </h1>

        <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-8">
          Last Updated: June 25, 2026
        </p>

        <div className="space-y-6 text-zinc-700 dark:text-zinc-300 leading-7">

          <p>
            ReviewReply AI provides AI-generated responses, suggestions, and analytics for informational and business assistance purposes only.
          </p>

          <div>
            <h2 className="text-xl font-semibold mb-2 text-black dark:text-white">
              AI-Generated Content
            </h2>

            <p>
              While we strive to provide accurate and helpful responses, AI-generated content may occasionally contain inaccuracies, incomplete information, or unsuitable suggestions.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2 text-black dark:text-white">
              User Responsibility
            </h2>

            <p>
              Users are solely responsible for reviewing, editing, and approving all generated replies before publishing or using them publicly.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2 text-black dark:text-white">
              No Professional Advice
            </h2>

            <p>
              The content generated by ReviewReply AI should not be considered legal, financial, business, or professional advice.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2 text-black dark:text-white">
              Limitation of Liability
            </h2>

            <p>
              ReviewReply AI shall not be held liable for any business losses, reputation damage, customer disputes, platform penalties, or other issues resulting from the use of generated content.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2 text-black dark:text-white">
              Third-Party Platforms
            </h2>

            <p>
              ReviewReply AI is not affiliated with or endorsed by Google, Yelp, Trustpilot, or any third-party review platforms unless explicitly stated.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2 text-black dark:text-white">
              Contact
            </h2>

            <p>
              If you have any questions regarding this Disclaimer, you may contact us at:
            </p>

            <p className="mt-2 font-medium text-black dark:text-white">
              afnak6789@gmail.com
            </p>
          </div>

          <p className="pt-4 border-t border-zinc-200 dark:border-zinc-800">
            By using ReviewReply AI, you acknowledge and agree to this Disclaimer.
          </p>

        </div>

      </div>

    </div>
  );
}

